version: '3.8'

services:
  app:
    build: .
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=production
      - PORT=3020
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=business_crm
      - DB_PORT=3306
      - JWT_SECRET=your-production-jwt-secret
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=business_crm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data:
